script:
  - export GITHUB_URL="https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/boardgame-cantstop/boardgame-cantstop.github.io"
  - mkdir -p build
  - cp -frv index.html style.css build
  - git clone "$GITHUB_URL" site
  - rm -frv site/*
  - cp -frv build/* site
  - cd site
  - git config user.name "$GITHUB_USERNAME"
  - git config user.email "$GITHUB_USERMAIL"
  - git add --all
  - git commit -m "Build $TRAVIS_BUILD_NUMBER"
  - git remote set-url origin "$GITHUB_URL"
  - git push origin master
