version: '3.7'

services:
  app:
    image: node:latest
    volumes:
    - .:/ws
    entrypoint: /bin/sh -c 'yarn install && yarn dev; tail -f'
    working_dir: /ws/app
    ports:
    - 80:80
    environment:
      PORT: 80
      HOST: 0.0.0.0
