version: '3.7'

services:
  app:
    image: node:lts-alpine
    volumes:
    - .:/ws
    entrypoint: /bin/sh -c '/ws/app/config.sh; tail -f'
    working_dir: /ws/app
    ports:
    - 80:80
    environment:
      PORT: 80
      HOST: 0.0.0.0
